// <auto-generated />
using Customer.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customer.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Customer")
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Customer.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "Juan Jose Gonzales Mejias 1"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "Juan Jose Gonzales Mejias 2"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "Juan Jose Gonzales Mejias 3"
                        },
                        new
                        {
                            ClientId = 4,
                            Name = "Juan Jose Gonzales Mejias 4"
                        },
                        new
                        {
                            ClientId = 5,
                            Name = "Juan Jose Gonzales Mejias 5"
                        },
                        new
                        {
                            ClientId = 6,
                            Name = "Juan Jose Gonzales Mejias 6"
                        },
                        new
                        {
                            ClientId = 7,
                            Name = "Juan Jose Gonzales Mejias 7"
                        },
                        new
                        {
                            ClientId = 8,
                            Name = "Juan Jose Gonzales Mejias 8"
                        },
                        new
                        {
                            ClientId = 9,
                            Name = "Juan Jose Gonzales Mejias 9"
                        },
                        new
                        {
                            ClientId = 10,
                            Name = "Juan Jose Gonzales Mejias 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
